export interface AgencyInfo { a: string; n: string; }

export const DB: Record<string, AgencyInfo> = {
    // --- INTERAGENCY / STATEWIDE (INT) ---
    "11": { a: "INT", n: "IA-11 Pensacola & Tallahassee" },
    "12": { a: "INT", n: "IA-12 Pensacola & Tallahassee" },
    "13": { a: "INT", n: "IA-13 Pensacola & Tallahassee" },
    "14": { a: "INT", n: "IA-14 Pensacola & Tallahassee" },
    "21": { a: "INT", n: "IA-21 Lake City & Jax" },
    "22": { a: "INT", n: "IA-22 Lake City & Jax" },
    "23": { a: "INT", n: "IA-23 Lake City & Jax" },
    "24": { a: "INT", n: "IA-24 Lake City & Jax" },
    "31": { a: "INT", n: "IA-31 Orlando" },
    "32": { a: "INT", n: "IA-32 Orlando" },
    "33": { a: "INT", n: "IA-33 Orlando" },
    "34": { a: "INT", n: "IA-34 Orlando" },
    "41": { a: "INT", n: "IA-41 West Palm Beach" },
    "42": { a: "INT", n: "IA-42 West Palm Beach" },
    "43": { a: "INT", n: "IA-43 West Palm Beach" },
    "44": { a: "INT", n: "IA-44 West Palm Beach" },
    "51": { a: "INT", n: "IA-51 Miami & Key West" },
    "52": { a: "INT", n: "IA-52 Miami & Key West" },
    "53": { a: "INT", n: "IA-53 Miami & Key West" },
    "54": { a: "INT", n: "IA-54 Miami & Key West" },
    "61": { a: "INT", n: "IA-61 Fort Myers" },
    "62": { a: "INT", n: "IA-62 Fort Myers" },
    "63": { a: "INT", n: "IA-63 Fort Myers" },
    "64": { a: "INT", n: "IA-64 Fort Myers" },
    "71": { a: "INT", n: "IA-71 Tampa" },
    "72": { a: "INT", n: "IA-72 Tampa" },
    "73": { a: "INT", n: "IA-73 Tampa" },
    "74": { a: "INT", n: "IA-74 Tampa" },
    "81": { a: "INT", n: "Statewide 81 (Common)" },
    "82": { a: "INT", n: "Statewide 82 (Common)" },
    "83": { a: "INT", n: "Statewide 83 (Common)" },
    "84": { a: "INT", n: "Statewide 84 (Common)" },
    "220": { a: "INT", n: "IA-FTM61 Law Talk" },
    "221": { a: "INT", n: "IA-FTM62 Law Talk" },
    "222": { a: "INT", n: "IA-FTM63 Law Talk" },
    "223": { a: "INT", n: "IA-FTM64 Law Talk" },
    "1185": { a: "INT", n: "US Marshal JTF Ops-5" },
    // --- FHP TROOP A (Pensacola) ---
    "801": { a: "FHP", n: "Troop A Dispatch (Pensacola)" },
    "802": { a: "FHP", n: "Troop A Law Tac" },
    "805": { a: "FHP", n: "Pensacola Patrol-2" },
    "832": { a: "FHP", n: "Troop A Law Tac" },
    "833": { a: "FHP", n: "Troop A Law Tac" },
    "835": { a: "FHP", n: "Troop A Law Tac" },
    "836": { a: "FHP", n: "Troop A Law Tac" },
    "869": { a: "FHP", n: "Troop A Law Tac" },
    "891": { a: "FHP", n: "Troop A Law Tac" },
    "899": { a: "FHP", n: "Troop A Law Tac" },
    // --- FHP TROOP B (Lake City) ---
    "78": { a: "FHP", n: "Troop B Patch/Talk" },
    "1058": { a: "FHP", n: "Troop B Law Tac" },
    "1089": { a: "FHP", n: "Troop B Dispatch" },
    "1138": { a: "FHP", n: "Troop B Air" },
    "1154": { a: "FHP", n: "Troop B/C Mutual Aid" },
    // --- FHP TROOP C (Tampa/Lakeland) ---
    "35": { a: "FHP", n: "Troop C Patch" },
    "250": { a: "FHP", n: "Troop C Law Talk" },
    "289": { a: "FHP", n: "Brooksville PTL-1" },
    "290": { a: "FHP", n: "Brooksville PTL-2" },
    "317": { a: "FHP", n: "Troop C Law Talk" },
    "353": { a: "FHP", n: "Sarasota PTL-1" },
    "354": { a: "FHP", n: "Sarasota PTL-2" },
    "355": { a: "FHP", n: "Bradenton PTL-1" },
    "356": { a: "FHP", n: "Bradenton PTL-2" },
    "577": { a: "FHP", n: "Tampa Law Tac" },
    "582": { a: "FHP", n: "FHP Air (Tampa)" },
    "609": { a: "FHP", n: "Tampa Dispatch" },
    "610": { a: "FHP", n: "Lakeland PTL-2" },
    "752": { a: "FHP", n: "Troop C Law Talk" },
    // --- FHP TROOP D/K (Orlando/Turnpike) ---
    "230": { a: "FHP", n: "Turnpike (Lake Worth) Patch" },
    "231": { a: "FHP", n: "Turnpike (Lake Worth) Talk" },
    "249": { a: "FHP", n: "FHP 249 Law Talk" },
    "554": { a: "FHP", n: "Orlando PTL-1" },
    "555": { a: "FHP", n: "Orlando PTL-2" },
    "556": { a: "FHP", n: "Orlando Special Detail" },
    "557": { a: "FHP", n: "Orlando Traffic Homicide" },
    "1352": { a: "FHP", n: "Turnpike (Wildwood) CVE" },
    "1830": { a: "FHP", n: "Turnpike (Wildwood) Disp" },
    // --- FWC (Fish & Wildlife) ---
    "171": { a: "FWC", n: "Ocala Patch/Talk" },
    "296": { a: "FWC", n: "Wildlife Ops 4" },
    "297": { a: "FWC", n: "Wildlife Ops SAT" },
    "298": { a: "FWC", n: "Wildlife Ops LEOW" },
    "299": { a: "FWC", n: "Wildlife Ops 1" },
    "300": { a: "FWC", n: "Wildlife Ops 2" },
    "306": { a: "FWC", n: "Wildlife Ops Tampa" },
    "1251": { a: "FWC", n: "Ocala Region Tac" },
    "1377": { a: "FWC", n: "Ocala Region Tac" },
    "1426": { a: "FWC", n: "Ocala Dispatch" },
    // --- FDLE ---
    "34921": { a: "FDLE", n: "Intel Ops 1" },
    "35066": { a: "FDLE", n: "Emerg Mgmt Dispatch" },
    "35161": { a: "FDLE", n: "Intel Ops Tac" },
    "35449": { a: "FDLE", n: "Fire Marshal Disp" },
    "35578": { a: "FDLE", n: "Intel Ops Disp" },
    "35891": { a: "FDLE", n: "Intel Ops Tac" },
    // --- LOCAL AGENCIES (LOC) ---
    "36617": { a: "LOC", n: "Franklin SO Dispatch" },
    "36673": { a: "LOC", n: "Franklin EMS Dispatch" },
    "36674": { a: "LOC", n: "Weems Memorial Hosp" },
    "1300": { a: "LOC", n: "Walton Common (MA)" },
    "20753": { a: "LOC", n: "North Walton Fire Disp" },
    "20769": { a: "LOC", n: "South Walton Fire Disp" },
    "20801": { a: "LOC", n: "Walton EOC" },
    "20865": { a: "LOC", n: "Walton SO N. Disp" },
    "20866": { a: "LOC", n: "Walton SO S. Disp" },
    "20913": { a: "LOC", n: "Defuniak PD Patrol" },
    "21025": { a: "LOC", n: "Okeechobee SO Disp" },
    "21057": { a: "LOC", n: "Okeechobee Fire Disp" },
    "21089": { a: "LOC", n: "Okeechobee PD Disp" },
    "21127": { a: "LOC", n: "Okeechobee EOC" },
    "20241": { a: "LOC", n: "Levy SO Dispatch" },
    "20257": { a: "LOC", n: "Levy Fire Dispatch" },
    "1538": { a: "LOC", n: "Bradford SO Dispatch" },
    "36257": { a: "LOC", n: "Air Methods (AirCom)" },
    "36110": { a: "LOC", n: "DBS School Buses" },
    // --- RADIO TECHS / PUBLIC WORKS (TEC) ---
    "27": { a: "TEC", n: "Microwave/NOC 1" },
    "75": { a: "TEC", n: "MA/COM 1" },
    "76": { a: "TEC", n: "MA/COM 2" },
    "945": { a: "TEC", n: "Radio Techs 945" },
    "49937": { a: "TEC", n: "Radio Techs 937" },
    "49945": { a: "TEC", n: "Radio Techs 945" },
    // --- P25 ALACHUA (legacy SmartZone / GRUCom overrides) ---
    "12301": { a: "LOC", n: "ACSO Dispatch 1" },
    "12302": { a: "LOC", n: "ACSO Dispatch 2" },
    "12401": { a: "LOC", n: "ACFR Fire Main" },
    // --- SLERS-P25 (WACN BEE00 / SID 04D9) — live-observed via scanner GLG ---
    // Names below marked "obs" were confirmed from the scanner's own channel tags;
    // unverified ids are observed on the control channel but not yet named (the
    // RadioReference DB is the authority). EDACS TGs map to these as old÷16.
    "2057": { a: "LOC", n: "GPD A1 (Gainesville PD)" },
    "2067": { a: "LOC", n: "ACSO A6" },
    "2147": { a: "LOC", n: "ACSO A1 (Sheriff Dispatch)" },
    "2161": { a: "LOC", n: "ACSO B14" },
    "2105": { a: "LOC", n: "Alachua SLERS-P25 2105 (unverified)" },
    "2109": { a: "LOC", n: "Alachua SLERS-P25 2109 (unverified)" },
    "3097": { a: "LOC", n: "Alachua SLERS-P25 3097 (unverified)" },
    // --- EDACS SLERS talkgroups (RadioReference via ARC-XT; AFS->LID = ag*128+fleet*8+sub) ---
    "36": { a: "FHP", n: "FHP Tampa" },
    "37": { a: "FHP", n: "FHP Tampa" },
    "38": { a: "FHP", n: "FHP Tampa" },
    "39": { a: "FHP", n: "FHP Tampa" },
    "40": { a: "FHP", n: "FHP Tampa" },
    "45": { a: "FHP", n: "FHP Tampa" },
    "46": { a: "FHP", n: "FHP Tampa" },
    "47": { a: "FHP", n: "FHP Tampa" },
    "48": { a: "FHP", n: "FHP Tampa" },
    "59": { a: "FHP", n: "FHP 59" },
    "77": { a: "TEC", n: "MA/COM3" },
    "79": { a: "FHP", n: "FHP LakeCity" },
    "80": { a: "FHP", n: "FHP LakeCity" },
    "85": { a: "FHP", n: "FHP LakeCity" },
    "86": { a: "FHP", n: "FHP LakeCity" },
    "87": { a: "FHP", n: "FHP LakeCity" },
    "88": { a: "FHP", n: "FHP LakeCity" },
    "89": { a: "FHP", n: "FHP LakeCity" },
    "90": { a: "FHP", n: "FHP LakeCity" },
    "91": { a: "FHP", n: "FHP LakeCity" },
    "97": { a: "FHP", n: "FHP LakeCity" },
    "98": { a: "FHP", n: "FHP LakeCity" },
    "99": { a: "FHP", n: "FHP LakeCity" },
    "100": { a: "FHP", n: "FHP LakeCity" },
    "101": { a: "FHP", n: "FHP LakeCity" },
    "102": { a: "FHP", n: "FHP LakeCity" },
    "172": { a: "FWC", n: "FWC Ocala" },
    "173": { a: "FWC", n: "FWC Ocala" },
    "174": { a: "FWC", n: "FWC Ocala" },
    "175": { a: "FWC", n: "FWC Ocala" },
    "176": { a: "FWC", n: "FWC Ocala" },
    "177": { a: "FWC", n: "FWC Ocala" },
    "178": { a: "FWC", n: "FWC Ocala" },
    "179": { a: "FWC", n: "FWC Ocala" },
    "180": { a: "FWC", n: "FWC Ocala" },
    "181": { a: "FWC", n: "FWC Ocala" },
    "182": { a: "FWC", n: "FWC Ocala" },
    "183": { a: "FWC", n: "FWC Ocala" },
    "184": { a: "FWC", n: "FWC Ocala" },
    "185": { a: "FWC", n: "FWC Ocala" },
    "186": { a: "FWC", n: "FWC Ocala" },
    "229": { a: "FHP", n: "FHP Turnpike" },
    "233": { a: "FHP", n: "FHP Turnpike" },
    "234": { a: "FHP", n: "FHP Turnpike" },
    "235": { a: "FHP", n: "FHP Turnpike" },
    "236": { a: "FHP", n: "FHP Turnpike" },
    "237": { a: "FHP", n: "FHP Turnpike" },
    "238": { a: "FHP", n: "FHP Turnpike" },
    "239": { a: "FHP", n: "FHP Turnpike" },
    "240": { a: "FHP", n: "FHP Turnpike" },
    "241": { a: "FHP", n: "FHP Turnpike" },
    "242": { a: "FHP", n: "FHP Turnpike" },
    "243": { a: "FHP", n: "FHP Turnpike" },
    "301": { a: "FWC", n: "W1_WILD3" },
    "302": { a: "FWC", n: "W3_ACAD" },
    "303": { a: "FWC", n: "W3_TAC_A" },
    "304": { a: "FWC", n: "W1_FISH3" },
    "305": { a: "FWC", n: "W1_TAC6" },
    "307": { a: "FWC", n: "W1_TAC7" },
    "308": { a: "FWC", n: "W1_FISH4" },
    "358": { a: "FHP", n: "HF_SDET2" },
    "359": { a: "FHP", n: "HF_DET4" },
    "364": { a: "FHP", n: "HF_S/TRT" },
    "365": { a: "FHP", n: "FHP_DIGP" },
    "370": { a: "FHP", n: "FHP_SDET" },
    "371": { a: "FHP", n: "HF_SDET1" },
    "372": { a: "FHP", n: "HF_SDET2" },
    "440": { a: "LOC", n: "Capital Sec." },
    "578": { a: "FHP", n: "FHP Tampa 578" },
    "583": { a: "FHP", n: "FHP Tampa" },
    "586": { a: "FHP", n: "FHP Tampa" },
    "870": { a: "FHP", n: "Troop A 870" },
    "871": { a: "FHP", n: "Troop A 871" },
    "876": { a: "FHP", n: "Troop A 876" },
    "898": { a: "FHP", n: "Troop A 898" },
    "1059": { a: "FHP", n: "FHP Lake Cit" },
    "1060": { a: "FHP", n: "FHP Lake Cit" },
    "1090": { a: "FHP", n: "FHP Lake Cit" },
    "1121": { a: "FHP", n: "FHP Lake Cit" },
    "1122": { a: "FHP", n: "FHP Lake Cit" },
    "1123": { a: "FHP", n: "FHP Lake Cit" },
    "1124": { a: "FHP", n: "FHP Lake Cit" },
    "1137": { a: "FHP", n: "FHP Lake Cit" },
    "1145": { a: "FHP", n: "Orl M/A" },
    "1155": { a: "FHP", n: "FHP Lake Cit" },
    "1214": { a: "INT", n: "Interagency" },
    "1215": { a: "INT", n: "Interagency" },
    "1378": { a: "FWC", n: "FWC Ocala" },
    "1410": { a: "FWC", n: "FWC Ocala" },
    "1411": { a: "FWC", n: "FWC Ocala" },
    "1432": { a: "FWC", n: "FWC Ocala" },
    "1438": { a: "FWC", n: "FWC Ocala" },
    "1476": { a: "FWC", n: "FWC Ocala" },
    "1779": { a: "FHP", n: "Encrypted 1779" },
};

export const AG_COLORS: Record<string, string> = {
    FHP: '--ag-fhp', FDLE: '--ag-fdle', FWC: '--ag-fwc',
    LOC: '--ag-loc', INT: '--ag-int', TEC: '--ag-tec'
};

export function agClass(code: string): string { return `ag-${code || 'UNK'}`; }
export function agColor(code: string): string { return AG_COLORS[code] || '--ag-unk'; }
